runtime: python27
threadsafe: true
api_version: 1

module: gql-web

handlers:
- url: /static
  static_dir: static

- url: .*
  script: graphql_web_playground.application

libraries:
- name: jinja2
  version: "2.6"
